version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/pricetracker
      - MORALIS_API_KEY=your_moralis_api_key
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your_email
      - SMTP_PASS=your_email_password
    depends_on:
      - db
  
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pricetracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
